apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: component
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: kings
            - name: POSTGRES_PASSWORD
              value: kings@1995
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          name: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: component
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30432
      targetPort: 5432
  type: NodePort