---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitor
spec:
  replicas: 1
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: config
          hostPath:
            path: /Users/kings/data/grafana/grafana.ini
        - name: data
          hostPath:
            path: /Users/kings/data/grafana/data
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitor
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: grafana