version: '3.8'

services:
  mysql:
    image: mysql:latest
    #给容器命名
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /data/mysql/my.cnf:/etc/mysql/my.cnf
      - /data/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    user: mysql
    network_mode: mysql
    networks:
      - kings-net
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - /data/zookeeper/data:/data
    network_mode: zookeeper
    networks:
      - kings-net
  team-city:
    image: jetbrains/teamcity-server
    container_name: team-city
    restart: on-failure
    ports:
      - "8111:8111"
    networks:
      - kings-net
    network_mode: team-city
    volumes:
      - /data/teamcity/data:/data/teamcity_server/datadir
      - /data/teamcity/logs:/opt/teamcity/logs
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data
    networks:
      - kings-net
    network_mode: redis
networks:
  kings-net:
    external: true