apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitor
  labels:
    app: postgres-exporter
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://kings:E.FV0K88@postgres-svc.component:5432?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitor
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187        # Prometheus 抓取的端口
      targetPort: 9187  # 容器中监听的端口