apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_ADDR
              value: "redis://redis.component:6379"
            - name: REDIS_USER
              value: king
            - name: REDIS_PWD
              value: 9e8acdbe27242c09470aa04338b7694f599f259a9e4918f2ead07fe46354aa9c
          args:
            - '--redis.addr=$(REDIS_ADDR)'
            - '--redis.user=$(REDIS_USER)'
            - '--redis.password=$(REDIS_PWD)'
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitor
spec:
  ports:
    - name: http
      port: 9121
      targetPort: 9121
  selector:
    app: redis-exporter