---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: kings-env
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /nexus-data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /Users/lunkings/data/nexus

---
apiVersion: v1
kind: Service
metadata:
  namespace: kings-env
  name: nexus
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: nexus
      nodePort: 30081
  type: NodePort
  selector:
    app: nexus