---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: kings
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        managementBy: self
    spec:
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
              # 时区设置
            - name: timezone
              mountPath: /etc/localtime
          command: ["redis-server", "/data/conf/redis.conf"]  # 指定配置文件
---
apiVersion: v1
kind: Service
metadata:
  namespace: kings
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30000
  selector:
    app: redis
    managementBy: self
  type: NodePort