logging:
  level.com.kings.framework: trace
spring:
  application:
    name: kings-app
  redis:
    database: 8
    host: 10.181.18.183

spring.datasource.url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
spring.datasource.username: root
spring.datasource.password: password
