---
apiVersion: v1
kind: Namespace
metadata:
  name: kings-env
  annotations:
    sidecar.istio.io/inject: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kings-env
  labels:
    app: redis
    profile: env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      profile: env
  template:
    metadata:
      labels:
        app: redis
        profile: env
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /Users/lunkings/data/redis/data
---
#mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kings-env
  labels:
    app: mysql
    profile: env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      profile: env
  template:
    metadata:
      labels:
        app: mysql
        profile: env
    spec:
      volumes:
        - name: data
          hostPath:
            path: /Users/lunkings/data/mysql/data
        - name: conf
          hostPath:
            path: /Users/lunkings/data/mysql/my.cnf
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /etc/mysql/my.cnf
              name: conf