apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: component
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-config
          hostPath:
            path: /Users/kings/data/mysql/my.cnf
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          #            - name: mysql-config
          #              mountPath: /etc/mysql/my.cnf
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: kings
            - name: MYSQL_USER
              value: king
            - name: MYSQL_PASSWORD
              value: kings@1995
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: component
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      nodePort: 30306
      targetPort: 3306
  type: NodePort
  selector:
    app: mysql
