apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab-system
  labels:
    app: gitlab-runner
spec:
  replicas: 1
  template:
    metadata:
      name: gitlab-runner
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
            - mountPath: /var/run/docker.sock
              name: docker
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        - name: config
          hostPath:
            path: /Users/lunkings/data/gitlab-runner
      restartPolicy: Always
  selector:
    matchLabels:
      app: gitlab-runner
---