apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab-runner
  namespace: middleware
  labels:
    app: gitlab-runner
spec:
  serviceName: gitlab-runner
  replicas: 1
  template:
    metadata:
      name: gitlab-runner
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner
          image: gitlab/gitlab-runner:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
            - mountPath: /home/gitlab-runner
              name: data
      volumes:
        - name: data
          hostPath:
            path: /Users/kings/data/gitlab-runner/data
        - name: config
          hostPath:
            path: /Users/kings/data/gitlab-runner
      restartPolicy: Always
  selector:
    matchLabels:
      app: gitlab-runner
---