---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: component
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: timezone
              mountPath: /etc/localtime
          command: [ "redis-server", "/data/conf/redis.conf" ]  # 指定配置文件
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: component
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: redis
  type: NodePort