apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-exporter
  namespace: kings
spec:
  replicas: 1
  serviceName: mysql-exporter
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_SOURCE_NAME
              value: "exporter:exporter_password@(mysql:3306)/"
          ports:
            - containerPort: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: kings
spec:
  ports:
    - name: http
      port: 9104
      targetPort: 9104
  selector:
    app: mysql-exporter