apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage
  capacity:
    storage: 5Gi
  hostPath:
    path: "/Users/kings/data/mysql/data"

